apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      name: web-pod
  template:
    metadata:
      labels:
        name: web-pod
    spec:
      containers:
        - name: tomcat
          image: mysql:5.6
          ports:
          - name: http
            containerPort: 8080
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: toor