- hosts: all
  tasks:
  - name: Add Jenkins repository's key
    become: yes
    apt_key:
      url: https://pkg.jenkins.io/debian/jenkins.io.key
  - name: Add Jenkins repository
    become: yes
    apt_repository:
      repo: deb https://pkg.jenkins.io/debian-stable binary/
  - name: Update apt
    become: yes
    apt:
      update_cache: yes
  - name: Install Java
    become: yes
    apt:
      name: openjdk-8-jre
  - name: Install Jenkins
    become: yes
    apt:
      name: jenkins
  - name: Copy web SSH private key
    copy:
      src: ../ssh-keys/id_rsa
      dest: /home/vagrant/id_rsa
      mode: 400