- hosts: all
  tasks:
  - name: Update apt
    become: yes
    apt:
      update_cache: yes
  - name: Install MySQL
    become: yes
    apt:
      name: mysql-server
      state: present
  - name: Creates MySQL user, database and tables
    become: yes
    shell: mysql -u root < /home/vagrant/script.sql