apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  template:
    metadata:
      labels:
        name: db-pod
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: toor
